name: Reusable Workflow - Docker
on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
      dockerfile-path:
        required: false
        type: string
        default: './Dockerfile'
    # we define de secrets that we want to use in the reusable workflow
    secrets:
      registry-token:
        required: false
jobs:
  build-and-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3


     # REUTILIZAMOS tu Custom Action del lab anterior dentro de este workflow
      - name: Run and Security Scan the Docker image
        uses: ./.github/actions/security-check
        with:
          dockerfile-path: ${{ inputs.dockerfile-path }}
      # - name: Build the Docker image
      #   run: |
      #     docker build -t ${{ inputs.image-name }} -f ${{ inputs.dockerfile-path }} .
      - name: ✅ Success Report
        run: echo "La imagen ${{ inputs.image_name }} pasó todas las pruebas."