name: Test Docker 

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      docker-file:
        description: 'Escribe la ruta del Dockerfile (ej: Dockerfile o subcarpeta/Dockerfile)'
        required: true
        default: 'Dockerfile'

jobs:
  call-docker-ci:
    uses: ./.github/workflows/reusable-workflow-docker.yaml
    with:
      image-name: 'Dockerfile'
      dockerfile-path: './Dockerfile'
    # Si tuvieras secretos, los pasarías así:
    # secrets:
    #   registry_token: ${{ secrets.MI_TOKEN }}